trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  document: '{ "id": "1", "tempurature": "40" }'
  cosmosDbInstanceName: 'rutzsco-demo-database'
  dbName: 'measurement-database'
  containerName: 'measurements'
  partitionKeyName: 'id'
  partitionKeyValue: '1'
steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      ls

- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: 'Demo Account'
    scriptType: bash
    scriptLocation: scriptPath 
    scriptPath: 'createDocument.sh' 
    arguments:
      -Arg1 $(document) `
      -Arg2 $(masterKey) `
      -Arg3 $(cosmosDbInstanceName) `
      -Arg4 $(dbName) `
      -Arg5 $(containerName) `
      -Arg6 $(partitionKeyName) `
      -Arg7 $(partitionKeyValue)
    
