trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  document: '@document.json'
  cosmosDbInstanceName: 'rutzsco-demo-database'
  dbName: 'measurement-database'
  containerName: 'measurements'
  partitionKeyName: 'id'
  partitionKeyValue: '1'
steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      ls

- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: 'Demo Account'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'create-document.sh'
    arguments: '$(document) $(masterKey) $(cosmosDbInstanceName) $(dbName) $(containerName) $(partitionKeyName) $(partitionKeyValue)'
    
